### ISSUE TITLE
Netspoc Web api

### ISSUE THREAD

**Issue by gthieleb** [hknutzen/Netspoc-API#1]
Hallo, sehr interessantes Projekt und danke, dass du den Code der Allgemeinheit zur Verfügung stellst. 

Gibt es eigentlich auch eine Netspoc Web Api um mit dem Backend vom policy web zu kommunizieren? Mich interessiert in erster Linie get oder search um den Zustand von Firewallregeln für IP-Adressen zu validieren.

**Comment by hknutzen** [comment]
Das Frontend von Netspoc-Web (Policy-Web) benutzt ja bereits ein API, um mit dem Backend zu reden.
Allerdings ist dieses API nicht dokumentiert.
Es ist aber trotzdem einfach, die benötigten Teile des API zu erkunden.
Navigiere einfach mit dem Browser zu der Stelle in Netspoc-Web, die dich interessiert.
Öffne dann mit F12 die Entwickler-Tools, um die API-Calls anzuschauen.

Beispielsweise bei einer Suche siehst du die Anfrage:
https://SERVER/netspocweb/backend/service_list<https://server/netspocweb/backend/service_list>
mit den POST-Daten:
active_owner=xxx
history=p12345
search_ip1=10.1.0.0/21
…

Die so bestimmten API-Calls kannst du dann aus einer anderen Anwendung heraus nutzen.
Vorab ist es noch erforderlich, sich anzumelden und den erhalten Cookie bei den nachfolgenden API-Calls mitzusenden.
Verwende dazu
https://SERVER/netspocweb/backend/login
bzw.
https://SERVER/netspocweb/backend/ldap_login

Mir sind zwei interne Projekte bekannt, wo dieses Vorgehen erfolgreich angewendet wurde.

**Comment by gthieleb** [comment]
Danke für deine schnelle Antwort und den Tip, dann verfolge ich den Ansatz mit den Developertools mal weiter. Die Backend API ist dann also zwischen dem Policy-Web alt und neu aber unverändert?

**Comment by hknutzen** [comment]
Das neue Netspoc-Vue verwendet das gleiche Backend-API wie das bisherige Netspoc-Web.

**Comment by hknutzen** [comment]
Hallo, hast du den Ansatz weiter verfolgt? Erste Ergebnisse erzielt?
Kannst du Informationen teilen, in welchem Kontext du Netspoc einsetzt? Finde ich sehr spannend. 
Gerne auch in privater Email.

**Comment by gthieleb** [comment]
Hallo Heinz, sorry ich hatte die Kommentare leider nicht gesehen.
